[package]
name = "tpm"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
lto = true

[dependencies]
syscalls = { path = "../../../sys/interfaces/syscalls", version = "0.1.0" }
libsyscalls = { path = "../../../sys/lib/libsyscalls", version = "0.1.0" }
libtime = { path = "../../../sys/lib/libtime", version = "0.1.0" }
console = { path = "../../../sys/lib/console", version = "0.1.0" }
malloc = { path = "../../../sys/lib/malloc", version = "0.1.0" }
rref = { path = "../../lib/rref", version = "0.1.0" }
spin = { path = "../../../lib/spin-rs" }
protocol = { path = "../../../sys/interfaces/protocol", version = "0.1.0" }
platform = { path = "../../../sys/interfaces/platform", version = "0.1.0" }
usr = { path = "../../../sys/interfaces/usr", version = "0.1.0" }
b2histogram = "1.0"
byteorder = { version = "1.3.4", default-features = false }
tpm_device = { path = "../../../sys/interfaces/device/tpm", version = "0.1.0" }
bitflags = "1.*"
bitfield = "0.13.2"

[dependencies.num-traits]
version = "0.2.8"
default-features = false
