[package]
name = "redleaf"
version = "0.1.0"
authors = ["Anton Burtsev <aburtsev@uci.edu>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
x86 = "0.19.0"
spin = "0.5.2"
volatile = "0.2.3"
x86_64 = "0.7.5"
pc-keyboard = "0.3.1"
log = "0.4"
custom_error = { git = "https://github.com/gz/custom_error.git" }
slabmalloc = { git = "https://github.com/gz/rust-slabmalloc.git" }
pcid = { path = "./lib/pcid" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false
