[package]
name = "bdev_shadow"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[[bin]]
name = "bdev_shadow"
test = false
bench = false

[dependencies]
syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
interface = { path = "../../../../interface/generated" }
libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
malloc = { path = "../../../../lib/core/malloc" }
spin = { path = "../../../../lib/core/spin-rs" }
libmembdev = { path = "../../../../lib/external/libmembdev" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false
