[package]
name = "xv6fs"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
array-init = "0.1.1"
spin = { path = "../../../../lib/spin-rs" }
byteorder = { version = "1.2", default-features = false }
num-traits = { version = "0.2", default-features = false }
pc-keyboard = "0.3.1"
syscalls = { path = "../../../../sys/interfaces/syscalls", version = "0.1.0" }
usr_interface = { package = "usr", path = "../../../../sys/interfaces/usr", version = "0.1.0" }
libusr = { path = "../../../../sys/lib/libusr", version = "0.1.0" }
rv6_sync = { package = "sync", path = "../../lib/sync", version = "0.1.0" }
libsyscalls = { path = "../../../../sys/lib/libsyscalls", version = "0.1.0" }
libtime = { path = "../../../../sys/lib/libtime", version = "0.1.0" }
console = { path = "../../../../sys/lib/console", version = "0.1.0" }
malloc = { path = "../../../../sys/lib/malloc", version = "0.1.0" }
tls = { path = "../../../../sys/lib/tls", version = "0.1.0" }
utils = { path = "../../../../lib/utils", version = "0.1.0" }
rref = { path = "../../../../sys/lib/rref", version = "0.1.0" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[package.metadata.cargo-xbuild]
memcpy = false
