[package]
name = "xv6fs"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[dependencies]
array-init = "0.1.1"
spin = { path = "../../../../../lib/core/spin-rs" }
byteorder = { version = "1.2", default-features = false }
num-traits = { version = "0.2", default-features = false }
pc-keyboard = "0.3.1"
syscalls = { path = "../../../../../lib/core/interfaces/syscalls" }
usr_interface = { package = "usr", path = "../../../../../lib/core/interfaces/usr", version = "0.1.0" }
libusr = { path = "../../../../../lib/external/libusr" }
rv6_sync = { package = "sync", path = "../../lib/sync", version = "0.1.0" }
libsyscalls = { path = "../../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../../lib/core/libtime" }
console = { path = "../../../../../lib/core/console" }
malloc = { path = "../../../../../lib/core/malloc" }
tls = { path = "../../../../../lib/core/tls" }
utils = { path = "../../lib/utils" }
rref = { path = "../../../../../lib/core/rref" }
hashbrown = "0.7"

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[features]
default = [
    # "hashmap",
]

hashmap = []
