[package]
name = "usr"
version = "0.1.0"
authors = ["Dan Appel <appeld@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscalls = { path = "../syscalls/", version = "0.1.0" }
rref = { path = "../../lib/rref/", version = "0.1.0" }
