[package]
name = "xv6net"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[dependencies]
array-init = "0.1.1"
spin = { path = "../../../../../lib/core/spin-rs" }
byteorder = { version = "1.2", default-features = false }
num-traits = { version = "0.2", default-features = false }
syscalls = { path = "../../../../../lib/core/interfaces/syscalls" }
interface = { path = "../../../../../interface/generated" }
libusr = { path = "../../../../../lib/external/libusr" }
rv6_sync = { package = "sync", path = "../../lib/sync", version = "0.1.0" }
libsyscalls = { path = "../../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../../lib/core/libtime" }
console = { path = "../../../../../lib/core/console" }
malloc = { path = "../../../../../lib/core/malloc" }
tls = { path = "../../../../../lib/core/tls" }
utils = { path = "../../lib/utils" }
smolnet = { path = "../../../../lib/smolnet" }
redhttpd = { path = "../../../../lib/redhttpd" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.smoltcp]
path = "../../../../../lib/external/smoltcp"
default-features = false
features = ["alloc", "proto-ipv4", "socket-tcp", "socket-icmp", "ethernet"]

[dependencies.arrayvec]
version = "0.5.1"
default-features = false
