[package]
name = "ixgbe"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

#[lib]
#crate-type = ["staticlib"]
#test = false
#bench = false

[dependencies]
bitflags = "1.0.4"
b2histogram = "1.0"
byteorder = { version = "1.3.4", default-features = false }

libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
malloc = { path = "../../../../lib/core/malloc" }
rref = { path = "../../../../lib/core/rref" }
spin = { path = "../../../../lib/core/spin-rs" }
sashstore-redleaf = { path = "../../../../lib/external/sashstore" }
libbenchnet = { path = "../../../lib/libbenchnet" }
smolnet = { path = "../../../lib/smolnet" }
redhttpd = { path = "../../../lib/redhttpd" }

# Interfaces
syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
ixgbe_device = { path = "../../../../lib/devices/ixgbe" }
pci_driver = { path = "../../../../lib/core/interfaces/dev/pci/pci_driver" }
protocol = { path = "../../../../lib/core/interfaces/protocol" }
platform = { path = "../../../../lib/core/interfaces/platform" }
interface = { path = "../../../../interface/generated" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false

[dependencies.smoltcp]
path = "../../../../lib/external/smoltcp"
default-features = false
features = ["alloc", "proto-ipv4", "socket-tcp", "socket-icmp", "ethernet"]

[dependencies.arrayvec]
version = "0.5.1"
default-features = false

[features]
default = [
    #"nullnet",
]

nullnet = []
