[package]
name = "mkfs-rs"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[dependencies]
spin = { path = "../../lib/core/spin-rs" }
rref = { path = "../../lib/core/rref" }
nix = {version = "0.19.1"}
libc = {version = "0.2"}



