[package]
name = "rv6-mkfs"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[dependencies]
nix = {version = "0.19.1"}
bincode = {version = "1.3.1"}
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
