[package]
name = "membdev"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[[bin]]
name = "membdev"
test = false
bench = false

[dependencies]
libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
malloc = { path = "../../../../lib/core/malloc" }
spin = { path = "../../../../lib/core/spin-rs" }
bitflags = "1.0.4"
rref = { path = "../../../../lib/core/rref" }
libmembdev = { path = "../../../../lib/external/libmembdev" }

syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
usr = { path = "../../../../lib/core/interfaces/usr" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false

[features]
default = [
    "default-memdisk"
]
# Supply a default memdisk if an empty memdisk is given
default-memdisk = []
