[package]
name = "nvme"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[dependencies]
syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
libbenchnvme = { path = "../../../lib/libbenchnvme" }
malloc = { path = "../../../../lib/core/malloc" }
spin = "0.5.2"
bitflags = "1.0.4"
byteorder = { version = "1.2", default-features = false }
serde_derive = "1.0.101"
nvme_device = { path = "../../../../lib/devices/nvme" }
pci_driver = { path = "../../../../lib/core/interfaces/dev/pci/pci_driver" }
usr = { path = "../../../../lib/core/interfaces/usr" }
protocol = { path = "../../../../lib/core/interfaces/protocol" }
platform = { path = "../../../../lib/core/interfaces/platform" }
libdma = { path = "../../../../lib/devices/libdma" }
rref = { path = "../../../../lib/core/rref" }
b2histogram = "1.0"

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dependencies.num-traits]
version = "0.2.8"
default-features = false

[features]
default = [
    # "nullnvme"
]

#rng_test = []
# Makes calls to nvme noop
nullnvme = []
