# xbuild with all possible combinations of flags
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    container: gitlet/redleaf_build:latest

    strategy:
      matrix:
        debug: ["true", "false"]
        ixgbe: ["true", "false"]
        large_mem: ["true", "false"]

    name: DEBUG=${{ matrix.debug }} IXGBE=${{ matrix.ixgbe }} LARGE_MEM=${{ matrix.large_mem }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  make DEBUG=${{ matrix.debug }} IXGBE=${{ matrix.ixgbe }} LARGE_MEM=${{ matrix.large_mem }}
