# xbuild with all possible combinations of flags
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        debug: ["false"]
        large_mem: ["true", "false"]

    name: DEBUG=${{ matrix.debug }} LARGE_MEM=${{ matrix.large_mem }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v12
      - name: Build
        run:  nix-shell --command "make DEBUG=${{ matrix.debug }} LARGE_MEM=${{ matrix.large_mem }}"
