# xbuild with all possible combinations of flags
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        debug: ["true", "false"]
        ixgbe: ["true", "false"]
        large_mem: ["true", "false"]

    name: DEBUG=${{ matrix.debug }} IXGBE=${{ matrix.ixgbe }} LARGE_MEM=${{ matrix.large_mem }}

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y nasm
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-22
          profile: minimal
          components: rust-src
          default: true
      - name: Build
        run:  make DEBUG=${{ matrix.debug }} IXGBE=${{ matrix.ixgbe }} LARGE_MEM=${{ matrix.large_mem }}
