# run unittests
name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        mode: ["dev", "release"]

    name: Run test in release(${{ matrix.mode }}) mode

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Nix
        uses: cachix/install-nix-action@v12
      - name: Test
        run: nix-shell --command "cargo test -Z unstable-options --manifest-path lib/core/rref/Cargo.toml --profile ${{ matrix.mode }}"
